services:
  api:
    image: 879366471942.dkr.ecr.us-east-2.amazonaws.com/zenvy/backend:latest
    container_name: zenvy_api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgres:15
    container_name: zenvy_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
