spring.application.name=zenvy-backend

//BD
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

//JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

//img config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#JWT configuration
security.jwt.secret-key=xJH3d9k2vQkM1sZC8ZP1m4+Z8vM9ZKp1Vx8eKk3cN9A=
# 1h in millisecond
security.jwt.expiration-time=3600000
# Refresh token 7 dias
security.jwt.refresh-expiration-time=604800000