name: Build and Push API

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::879366471942:role/ZenvyGithubActionsRole
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker Image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -t $ECR_REGISTRY/zenvy/backend:latest \
            .
      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push $ECR_REGISTRY/zenvy/backend:latest

      - name: Test SSM
        run: |
          aws ssm send-command \
            --instance-ids i-0b558f42bb54aefcb \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["mkdir -p /tmp/zenvy-ssm-test", "echo Created by GitHub Actions through SSM > /tmp/zenvy-ssm-test/test.txt"]' \
            --region us-east-2